### ISSUE TITLE
Implement missing aggregations

### ISSUE THREAD

**Issue by Douglasdc3** [AviationCode/elasticsearch#20]
When implementing new aggregations make a PR per aggregation, Add tests and reference this issue in your PR

List of aggregations

Metrics
- [x] avg
- [x] weighted avg
- [x] cardinality
- [x] extended stats
- [x] geo bounds
- [x] geo centroid
- [x] max
- [x] min
- [x] percentiles
- [x] percentile rank
- [x] ~scripted~
- [x] stats
- [x] string_stats
- [x] sum
- [x] top hits
- [X] value count 
- [x] median absolute deviation

Bucket
- [x] adjacency matrix
- [x] auto interval date histogram
- [x] children
- [ ] composite
- [x] date histogram
- [x] date range
- [x] diversified sampler
- [x] filter
- [x] filters
- [x] geo distance
- [x] geohash grid
- [x] geotile grid
- [x] global
- [x] histogram
- [x] ip range
- [x] missing
- [x] nested
- [x] parent
- [x] range
- [x] rare terms
- [x] revere nested
- [x] sampler
- [x] significant terms
- [x] significant text
- [x] terms

Pipeline
- [x] avg bucket
- [x] derivative
- [x] max bucket
- [x] min bucket
- [x] sum bucket
- [x] stats bucket
- [x] extended stats bucket
- [x] percentiles bucket
- [x] moving average
- [x] moving function
- [x] cumulative sum
- [x] cumulative cardinality
- [x] ~bucket script~
- [x] bucket selector
- [x] bucket sort
- [x] serial differencing

Documentation: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations.html

**Comment by hamzahejja** [comment]
@Douglasdc3 The Class AviationCode\Elasticsearch\Query\Aggregations#Aggregation.php extends `Illuminate\Support\Collection` and the magic method `__call($method, $arguments)` is implemented to call forward calls such as `->valueCount()` to the designated agg. class through an internal function within the same class which is `$addAggregation()` , However for the **Metric Aggregations**: _avg, min, max, sum_  are all implemented through the parent class (i.e. Collection) , therefore the magic call __call won't do the job because it'll never be reached for those functions. One solution is to override those functions in the `Aggregation` class. An other solution which I don't prefer, is to name the aggregation classes differently, hence "min" cannot have the corresponding class Min, etc ... What's your call here ?

**Comment by Douglasdc3** [comment]
> @Douglasdc3 The Class AviationCode\Elasticsearch\Query\Aggregations#Aggregation.php extends `Illuminate\Support\Collection` and the magic method `__call($method, $arguments)` is implemented to call forward calls such as `->valueCount()` to the designated agg. class through an internal function within the same class which is `$addAggregation()` , However for the **Metric Aggregations**: _avg, min, max, sum_ are all implemented through the parent class (i.e. Collection) , therefore the magic call __call won't do the job because it'll never be reached for those functions. One solution is to override those functions in the `Aggregation` class. An other solution which I don't prefer, is to name the aggregation classes differently, hence "min" cannot have the corresponding class Min, etc ... What's your call here ?

A good catch not something I taught about when creating this class. I'm not big fan either that I had to extend the Aggregation class from `Collection`.  I'll take a look at this one!

Thanks for the feedback

**Comment by Douglasdc3** [comment]
@hamzahejja I have fixed the this issue by using composition over inheritance in the latest commit. Thanks again for the good catch!

**Comment by hamzahejja** [comment]
@Douglasdc3 No Problem! Thanks for the fast response

**Comment by hamzahejja** [comment]
@Douglasdc3 I'm more than happy to implement a big load of the aggregations mentioned above. However, I must ask you, is it possible to implement multiple aggregations at once (i.e. within same PR) ? Because you've explicitly mentioned to open a separate PR for every implemented aggregation, So we'll go on your command here, it'll be your decision!

**Comment by Douglasdc3** [comment]
@hamzahejja would greatly appreciate if you be willing to add a whole bunch of these. The reason I mentioned a single one for a PR is to simplify review process and avoid merge conflicts.

If you are willing to take up more just mention them here so other people do not start on the same ones!

**Comment by hamzahejja** [comment]
@Douglasdc3 At the moment, I'm willing to take on/implement the following from **Metrics Aggregations**:
- avg
- sum
- stats
- percentiles
- extended stats
- weighted avg
- geo-bounds
- geo-centroid
